
jwt:
  secret : "SequenciaDecaracteresParaAssinarToken"
  expiration: 90000


spring:
  jpa:
   show-sql: true
  hibernate:
   ddl-auto: update
  show-sql: true

  properties:
    hibernate:
      format_sql: true

  database-platform: br.com.wrs.config.dialectConfig.PostgresDialect95Config
  datasource:
    url: jdbc:postgresql://localhost:5432/worshipscales
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver